name: Scheduled
on:
    schedule:
        - cron: '*/5 * * * *'
jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "The current server time is $(date)"
